server:
  port: 80

spring:
  thymeleaf:
    encoding: UTF-8
    mode: HTML
    cache: false
  mvc:
    static-path-pattern: /static/**

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/makeup?serverTimezone=GMT%2B8&characterEncoding=UTF-8
    username: root
    password: root


  mail:
    host: smtp.qq.com
    username: 1329148394@qq.com
    password: uwmriieemzrajgah
    default-encoding: utf-8


  redis:
    database: 0
    host: 127.0.0.1
    port: 6379
    timeout: 3000ms
