server:
  port: 80
  servlet:
    context-path: /makeup

spring:
  thymeleaf:
    encoding: UTF-8
    mode: html5
    cache: false




#spring:
#  datasource:
#    driver-class-name: com.mysql.cj.jdbc.Driver
 #   url: jdbc:mysql://localhost:3306/test
  #  username: root
  #  password: root
